faceXAadhar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('face_app.urls')),
]

face_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views
urlpatterns = [
    path('', views.intro,name='front'),
    path('doctor/', include('django.contrib.auth.urls')),
    path('aadharlogin/', views.aadharlogin, name='aadharlog'),
    url(r'^details/(?P<id>\d+)/files/$', views.files, name='files'),
    url(r'^details/(?P<id>\d+)/files/new/$', views.newfiles, name='newfiles'),
    path('pharma/', views.pharmacy, name='pharmacy'),
    path('pharma/otpa/', views.otpa, name='otpa'),
    path('pharma/otpa/<int:id>/', views.otparecord, name='otpa_record'),
    path('patient/', views.patient, name='patient'),

]

face_app/models.py
from django.db import models

# Create your models here.
class Record(models.Model):
    aadhar_no = models.IntegerField(primary_key = True)
class Files(models.Model):

    aadhar_no = models.IntegerField(max_length=12)
    date_of_visiting = models.CharField(max_length=11,null=True)
    symptoms = models.TextField(max_length=300,null=True)
    drugs = models.TextField(max_length=300,null=True)
    dosage = models.TextField(max_length=300,null=True)
    tests_to_be_done = models.TextField(max_length=300,null=True)
    date_for_revisit = models.CharField(max_length=11,null=True)

face_app/forms.py
from django import forms

class AadharForm(forms.Form):
    aadhar_no = forms.IntegerField()

class OtpaAadharLogin(forms.Form):
    otpa = forms.IntegerField()


class NewFileForm(forms.Form):
    dov = forms.CharField(max_length=11,
    widget = forms.Textarea(attrs={
    'rows':1,
    })
    )
    symptoms_p = forms.CharField(max_length=300,
    widget = forms.Textarea(attrs={
    'rows':5,
    })
    )
    drugs_p = forms.CharField(max_length=300,
    widget = forms.Textarea(attrs={
    'rows':5,
    })
    )
    dosage_p = forms.CharField(max_length=300,
    widget = forms.Textarea(attrs={
    'rows':5,
    })
    )
    tests_to_be_done_p = forms.CharField(max_length=300,
    widget = forms.Textarea(attrs={
    'rows':5,
    }))
    date_for_revisit = forms.CharField(max_length=11,
    widget = forms.Textarea(attrs={
    'rows':1,
    })
    )

face_app/views.py
from django.shortcuts import render
from .forms import AadharForm, OtpaAadharLogin, NewFileForm
from random import randint
from .models import Files, Record
# Create your views here.

def intro(request):
    return render(request,'intro1.html')

def aadharlogin(request):
    if request.method == "GET":
        form = AadharForm()
        return render(request, 'index.html',{'form':form})
    if request.method == "POST":
        form = AadharForm(request.POST)
        import requests
        url = "https://aadhaarverify.p.rapidapi.com/Uidverify"

        querystring = {"uidnumber":request.POST['aadhar_no'],"txn_id":"123456","consent":"Y"}

        payload = ""
        headers = {
        'x-rapidapi-host': "aadhaarverify.p.rapidapi.com",
        'x-rapidapi-key': "4f23e025ddmsh893b101357d4f77p1e07f0jsn57cd65c2d554",
        'content-type': "application/x-www-form-urlencoded"
        }

        response = requests.request("POST", url, data=payload, headers=headers, params=querystring)

        r = response.json()
        print(r["Succeeded"]["Verify_status"])
        range_start = 10**(3)
        range_end = (10**4)-1
        a = randint(range_start, range_end)
        print("otpa:",a)
        try:
            p = Record(aadhar_no = request.POST['aadhar_no'])
            p.save()
        except Exception as e:
            pass
        return render(request, 'otpa_doctorpanel.html', {'a':a,'a_no':request.POST['aadhar_no']})

    return render(request, 'index.html')


def files(request, id):
    record = Record.objects.get(aadhar_no = id)
    file = Files.objects.filter(aadhar_no = id)
    if not file:
        empty = True
        return render(request, 'files.html', {'empty':empty,'aadhar_num': id})
    else:
        empty = False
        context = {
            'record': record,
            'file':file,
            'empty':empty,
            'aadhar_num': id,
        }

    return render(request, 'files.html', context)




def newfiles(request,id):
    record = Record.objects.get(aadhar_no=id)
    if request.method=="POST":
        form = NewFileForm(request.POST)
        if form.is_valid():
            new_req = Files(aadhar_no=id,date_of_visiting=request.POST.get('date_of_visiting'),symptoms=request.POST.get('symptoms'),drugs=request.POST.get('drugs'),dosage=request.POST.get('dosage'),tests_to_be_done=request.POST.get('tests_to_be_done'),date_for_revisit=request.POST.get('date_for_revisit'))
            new_req.save()
            return render(request,'done.html',{'record':record})
    else:
        file = Files.objects.filter(aadhar_no = id)
        form = NewFileForm()
        context = {
            'form':form,
            'record':record,
            }
        return render(request,'newfile.html',context)



def pharmacy(request):
    number = Record.objects.all()
    val = number
    context = {
    'number' : number
    }
    return render(request,'pharma.html',context)

def otpa(request):
    range_start = 10**(3)
    range_end = (10**4)-1
    a = randint(range_start, range_end)
    print(a)
    context = {
    'a':a
    }
    return render(request,'otpa.html',context)
def otparecord(request,id):
    # record_s = Records.objects.all()
    # file = Files.objects.all()
    # context = {
    # 'record_s':record_s,
    # 'file':file
    # }
    record = Record.objects.get(aadhar_no=id)
    file = Files.objects.filter(aadhar_no = id)
    context = {
        'record' : record,
        'file':file,
    }
    return render(request,'record_search.html',context)

def patient(request):
    number = Record.objects.all()
    val = number
    context = {
    'number' : number
    }
    return render(request,'patient.html',context)

templates/details.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}Image Recognition{% endblock %}
{% block content %}
<div class="container">
  <div style="padding-bottom: 2em;text-align:center">
    <h1 class="text-center" style="color:#047c2a">TOP MATCH</h1>
    <p>The classifier predicts the person that matches the given face with our top database face. Thus the accuracy might get compromised.*</p>
  </div>

  <!-- <ul>
    <li>{{record.first_name}} {{record.last_name}}</li>
    <li>{{record.occupation}}</li>
    <li>{{record.residence}}, {{record.country}}</li>
  </ul> -->
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1" style="padding-top:3em;padding-bottom:3em;-webkit-box-shadow: 0px 0px 14px 0px rgba(50, 50, 50, 0.5);
-moz-box-shadow:    0px 0px 14px 0px rgba(50, 50, 50, 0.5);
box-shadow:         0px 0px 14px 0px rgba(50, 50, 50, 0.5);">
        <!-- <div class="col-md-5">
          <div class="row"> -->
            <!-- <div class="col-md-8 col-md-offset-2">
              <img src="{% static '' %}img/{{record.id}}.jpg" class="img-responsive" style="border-radius:50%"/>
            </div> -->
            <div class="col-md-12" style="text-align:center">
              <h3 style="color:#d18f02;font-size:55px;"><b>{{record.first_name}} {{record.last_name}}</b></h3>
              <h5 style="text-align:center;padding-right:170px;"><b>id: </b> {{record.id}} </h5>
              <h5><b>E-mail: </b> {{record.email}} </h5>
              <h5 style="text-align:center;padding-right:140px;"><b>Sex: </b> {{record.sex}}</h5>
              <h5 style="text-align:center;padding-right:25px;"><b>Date of birth: </b> {{record.dob}}
              <h5 style="text-align:center;padding-right:40px;"><b>Phone No.: </b> {{record.phone}}</h5>
            </div>
          <!-- </div>
        </div> -->
        <div class="col-md-7">

        </div>
        <div class="col-md-12" style="margin-top:2em">
          <a href="/" class="btn btn-warning"><i class="fa fa-chevron-left" aria-hidden="true"></i> Home</a>
          <a href="/records/details/{{record.id}}/files/" class="btn btn-warning" style='float:right';>Continue <i class="fas fa-chevron-right"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/done.html
<h1>Prescription Submitted </h1>


<a href="{% url 'front' %}"> <button style="margin-left:10px;border-radius:6px;width:160px;font-size:30px">Home</button></a>

templates/error.html
{% extends 'layout.html' %}

{% load static %}
{% block title %}MedEazy{% endblock %}
{% block content %}
<div class="container" style="height:88vh">
  <div style="padding-bottom: 2em;">
    <h1 class="text-center jumbotron">Oops something went wrong! <i class="fa fa-frown-o" aria-hidden="true"></i>
</h1>
    <h3>Our Suggestion</h3>
    <p><i class="fa fa-dot-circle-o" aria-hidden="true"></i> Make sure the your image has clear visible face with no obstruction and try again. <i class="fa fa-smile-o" aria-hidden="true"></i></p>
  </div>
  <a href="/" class="btn btn-warning"><i class="fa fa-chevron-left" aria-hidden="true"></i> Back</a>
</div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% load static %}
{% block title %}MedEazy{% endblock %}
{% block content %}
<div id="particles-js"></div>
<div class="container" >
  <div class="col-lg-12" style="background: rgba(0,0,0,0.6);margin-top:3em;margin-bottom:5em;padding-top:1em;padding-bottom:3em;color:#fff;border-radius:10px;-webkit-box-shadow: 2px 2px 15px 0px rgba(0, 3, 0, 0.7);
-moz-box-shadow:    2px 2px 15px 0px rgba(0, 3, 0, 0.7);
box-shadow:         2px 2px 15px 0px rgba(0, 3, 0, 0.7);">
    <div class="col-lg-12">




      <h1 class="text-center section-title" style="margin-bottom:2em;margin-left:70px;">MedEazy</h1>
    </div>
    <style>
      h4{
        margin-bottom: 1.5em;
      }
      img{
        border-radius:50%;
        -webkit-transition: all 0.3s ease-in-out;
    -moz-transition: all 0.3s ease-in-out;
     transition: all 0.3s ease-in-out;
      }
      img:hover{
        -webkit-box-shadow: 2px 2px 21px 0px rgba(0, 3, 0, 0.91);
        -moz-box-shadow:    2px 2px 21px 0px rgba(0, 3, 0, 0.91);
        box-shadow:         2px 2px 21px 0px rgba(0, 3, 0, 0.91);
        border:2px solid #fff;
      }
      h3{
        margin-bottom: 1.3em;
      }
      a{
        color:inherit
      }
      a:hover{
        color:inherit;
        text-decoration: none;
      }
      /* .section-title:after {
        	content:' ';display:block;margin:0 auto;width:100px;margin-top: 6px;border:2px solid #d0d0d0;border-radius:4px;
        	-webkit-border-radius:4px;
        	-moz-border-radius:4px;
        	box-shadow:inset 0 1px 1px rgba(0, 0, 0, .05);
        	-webkit-box-shadow:inset 0 1px 1px rgba(0, 0, 0, .05);
        	-moz-box-shadow:inset 0 1px 1px rgba(0, 0, 0, .05);
          margin-bottom:1em;
        } */
        input {
          background-color: grey;
        }
        label{
          font-size:40px;
        }
        #id_aadhar_no{
          height:35px;
          margin-left:10px;
          width:400px;
        }
    </style>

<!-- for under faceX -->

  {% if form %}
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p  }}
    <input type="submit" style="margin-left:10px;border-radius:6px;width:160px;font-size:30px">



  </form>
  {% endif %}

</div><!-- Container -->





{% endblock %}

templates/intro1.html
{% load static %}
<!DOCTYPE html>
<html>
    <style>
        *{
    margin: 0px;
    padding: 0px;
    box-sizing: border-box;
         }
         body
         {
           background-color: black;
           background:url("{% static 'img/doc4.jpg' %}");
            background-repeat: no-repeat;
    background-size: 100%;
    background-position: center;
    background-attachment: fixed;
    opacity: 1;
        }
        header{
    /*background-color: white;*/
    padding: 20px;
    border-color:#24272e;
    border-style: solid;
        }
        header h1{
    color:#24272e;
    text-align: center;
    font-size: 50px;
    font-weight: bold;
    font-family: 'Courier New', Courier, monospace;
        }
        /*.buttons{
           margin-left: 530px;
           margin-top: 300px;
        }
        .btn{
            background-color: #24272e;
            color:white;
            border-color: black;
            padding:0px 20px;
        }*/
        .scoreboard{
    border:3px solid #24272e;
    opacity: 0.7;
    border-radius: 170px;
    width: 600px;
    height: 200px;
    margin :220px auto;
    text-align: center;
    color: white;
    font-size: 40px;
    padding: 15px 20px;
    font-family: 'Courier New', Courier, monospace;
    position: relative;


}
.badge{
    background-color: #24272e;
    opacity: 1;
    color: white;
    font-size: 14px;
    padding: 20px 50px;
    font-family: 'Courier New', Courier, monospace;
    border-radius: 70px;
   }
   .badge1{
       width:500px;
       padding: 20px 50px;
    font-family: 'Courier New', Courier, monospace;
    color: white;
    margin-left: 30px;
    border-radius: 70px;
   }
#user{
    position: absolute;
    top: 60px;
    left: -145px;
}
#computer{
    position: absolute;
    top: 60px;
    right: -165px;
}
#pharmacy{
    position: absolute;
    top: 150px;



}
#button1{
    background-color: #24272e;
    border-color: #24272e;
    font-family: 'Courier New', Courier, monospace;
    color: white;
    border-style: none;
    font-weight: bold;
    font-size: 30px;
}
#button2{
    background-color: #24272e;
    border-color: #24272e;
    font-family: 'Courier New', Courier, monospace;
    color: white;
    border-style: none;
    size: 40px;
    font-weight: bold;
    font-size: 30px;

}
#button3{
    background-color: #24272e;
    border-color: #24272e;
    font-family: 'Courier New', Courier, monospace;
    color: white;
    border-style: none;
    size: 40px;
    font-weight: bold;
    font-size: 30px;
    padding: 25px 40px;
    border-radius: 70px;

}
#button1:hover{
    cursor: pointer;
}
#button2:hover{
    cursor: pointer;
}
#button3:hover{
    cursor: pointer;
}

.badge:hover{
    cursor: pointer;
    border-color: white;
    border-width: 2px;
}
        </style>
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <header><h1>MedEazy</h1></header>
        <!--<div class="buttons">
            <button class="btn" id="button1"><h1>I'm a Patient</h1></button>
            <button class="btn" id="button2"><h1>I'm a Doctor</h1></button>
        </div>-->
        <div class="scoreboard">
            <div id="user" class="badge"> <a href="{% url 'patient' %}"><button type="button" id="button1">I'm a Patient</button></a></div>
             <div id="computer" class="badge"><a href="/doctor/login/"><button type="button" id="button2">I'm a Doctor</button></a></div>
             <div id="pharmacy" class="badge1"><a href="{% url 'pharmacy' %}"><button type="button" id="button3">Pharmacist</button></a></div>
             <span id="user_score">    </span> <span id="computer_score">    </span>
         </div>

    </body>
</html>

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.jpg' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'jquery.min.js' %}"></script>
    <link rel="stylesheet"href=" https://fonts.googleapis.com/css?family=Muli:400,600">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />

  </head>

  <body>

    {% block content %}
    {% endblock %}
    <!-- Custom scripts for this template -->
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/particles.min.js' %}" ></script>
    <script src="{% static 'script.js' %}"></script>

  </body>

</html>

templates/newfile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  <title>Document</title>
</head>
<body>
  <style>

 #id_patient_id{
   width:100px;
 }
 #id_dov{
   width:120px;
 }
 #id_date_for_revisit{
    width:120px;
 }

  </style>


  <h1 style="text-align:center;font-weight:bolder;font-family: 'Courier New', Courier, monospace;font-size:70px">New Prescription</h1><br>
  <a href="{% url 'files' record.pk %}"> <button style="margin-left:10px;border-radius:6px;">All prescriptions</button></a>
  <a href="{% url 'front' %}"> <button style="margin-left:10px;border-radius:6px;width:80px">Home</button></a>





  <form method="POST">
    {% csrf_token %}

    <table class="table table-striped">
    <thead>
      <tr>

        <th scope="col">Date of visiting</th>
        <th scope="col">Symptoms</th>
        <th scope="col">Drugs</th>
        <th scope="col">Dosage</th>
        <th scope="col">Test to be done</th>
        <th scope="col">Date for revisit</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        
        <td>{{form.dov}}</td>
        <td>{{form.symptoms_p}}</td>
        <td>{{form.drugs_p}}</td>
        <td>{{form.dosage_p}}</td>
        <td>{{form.tests_to_be_done_p}}</td>
        <td>{{form.date_for_revisit}}</td>
      </tr>

    </tbody>
  </table>
  <br>
  <input type="submit" value="Prescription Done" style="margin-left:700px;font-size:20px;border-radius:6px;">


    <!-- Patient No: {{form.patient_id}}<br>
    Date of visiting: {{form.dov}}<br>
    Symptoms: {{form.symptoms_p}}<br>
    Drugs: {{form.drugs_p}}<br>
    Dosage: {{form.dosage_p}}<br>
    Test to be done: {{form.tests_to_be_done_p}}<br>
    Date for revisit: {{form.date_for_revisit}}<br>
    <input type="submit"> -->
  </form>

</body>
</html>

templates/otpa_doctorpanel.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
  body{
    background: #636363;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #a2ab58, #636363);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #a2ab58, #636363); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

  }
  input{
    width:200px;
    height:30px;
    border-radius:10px;
  }
  button{
    width:180px;
    height:40px;
    margin-left:630px;
    border-radius:7px;
    font-weight:bold;
  }
  a{
    margin-top:40px;
    color:inherit;
    margin-left:500px;
    font-weight:bold;
    font-size:30px;

  }
  </style>
</head>
<body>

  <h1 style="font-size:50px;color:white;margin-left:500px;">Enter OTPA: <input type="text" id="myText"> </h1>
  <button onclick="myFunction()">Submit</button>
  <h1 style="font-size:50px;color:white;margin-left:500px;" id="myText2"> </h1>
  <script>
    function myFunction() {
      var x = document.getElementById("myText").value;
      var y = {{a}}
      if (x==y){
        document.getElementById("myText2").innerHTML = "Successfully Authenticated";
        var a = document.createElement('a');
var linkText = document.createTextNode("Continue");
a.appendChild(linkText);
a.href = "{% url 'files' a_no %}";
document.body.appendChild(a);

      }
      else{
        alert("Wrong OTPA");
      }

    }
  </script>

</body>
</html>

templates/patient.html
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>Document</title>
 <style>
    #myInput {
  background-image: url('/css/searchicon.png'); /* Add a search icon to input */
  background-position: 10px 12px; /* Position the search icon */
  background-repeat: no-repeat; /* Do not repeat the icon image */
  width: 100%; /* Full-width */
  font-size: 16px; /* Increase font-size */
  padding: 12px 20px 12px 40px; /* Add some padding */
  border: 1px solid #ddd; /* Add a grey border */
  margin-bottom: 12px; /* Add some space below the input */
}

#myUL {
  /* Remove default list styling */
  list-style-type: none;
  padding: 0;
  margin: 0;
}

#myUL li a {
  border: 1px solid #ddd; /* Add a border to all links */
  margin-top: -1px; /* Prevent double borders */
  background-color: #f6f6f6; /* Grey background color */
  padding: 12px; /* Add some padding */
  text-decoration: none; /* Remove default text underline */
  font-size: 18px; /* Increase the font-size */
  color: black; /* Add a black text color */
  display: block; /* Make it into a block element to fill the whole list */
}

#myUL li a:hover:not(.header) {
  background-color: #eee; /* Add a hover effect to all links, except for headers */
}
    </style>
</head>

<body>



    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Type Aadhar Card Number">

<ul id="myUL">
  <li><a href="{% url 'otpa' %}">790083600985</a></li>

  <!-- <li><a href="#">Agnes</a></li>

  <li><a href="#">Billy</a></li>
  <li><a href="#">Bob</a></li>

  <li><a href="#">Calvin</a></li>
  <li><a href="#">Christina</a></li>
  <li><a href="#">Cindy</a></li> -->
</ul>


   <script>
function myFunction() {
  // Declare variables
  var input, filter, ul, li, a, i, txtValue;
  input = document.getElementById('myInput');
  filter = input.value.toUpperCase();
  ul = document.getElementById("myUL");
  li = ul.getElementsByTagName('li');

  // Loop through all list items, and hide those who don't match the search query
  for (i = 0; i < li.length; i++) {
    a = li[i].getElementsByTagName("a")[0];
    txtValue = a.textContent || a.innerText;
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      li[i].style.display = "";
    } else {
      li[i].style.display = "none";
    }
  }
}
</script>


</body>

</html>

templates/record_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  <title>Document</title>
</head>
<body>
  <style>

 #id_patient_id{
   width:100px;
 }
 #id_dov{
   width:120px;
 }
 #id_date_for_revisit{
    width:120px;
 }

  </style>


  <h1 style="text-align:center;font-weight:bolder;font-family: 'Courier New', Courier, monospace;font-size:70px">All Registered Patients</h1><br>


  <form method="POST">
    {% csrf_token %}

    <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Patient No</th>
        <th scope="col">Patient Name</th>
        <th scope="col">Date of birth</th>
        <th scope="col">Record created at</th>
    </thead>
    <tbody>

      <tr>
        <th scope="row">{{recDetail.id}}</th>
        <td> {{recDetail.first_name}} {{recDetail.last_name}}</td>
        <td> {{recDetail.dob}}</td>
        <td> {{rec.recorded_created_at}}</td>


      </tr>

    </tbody>
  </table>
  <a href="{% url 'update_record' recDetail.pk %}" style="margin-left:700px">Edit this Record</a>
</body>
</html>








<!-- <h2>Record Details:</h2>
<p>{{recDetail.id}}</p>
<p>{{recDetail.first_name}} {{recDetail.last_name}}</p>
<p>{{recDetail.dob}}</p>
<p>{{rec.recorded_created_at}}</p> -->

templates/record_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  <title>Document</title>
</head>
<body>
  <style>

 #id_patient_id{
   width:100px;
 }
 #id_dov{
   width:120px;
 }
 #id_date_for_revisit{
    width:120px;
 }

  </style>


  <h1 style="text-align:center;font-weight:bolder;font-family: 'Courier New', Courier, monospace;font-size:70px">All Registered Patients</h1><br>


  <form method="POST">
    {% csrf_token %}

    <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Patient No</th>
        <th scope="col">Patient Name</th>
    </thead>
    <tbody>
      {% for r in object_list %}
      <tr>
        <th scope="row"><a href="{% url 'detail_record' r.pk %}" style="font-size:20px;padding-left:20px;">{{r.id}}</a><br></th>
        <td> {{r.first_name}} {{r.last_name}}</td>

      </tr>
        {% endfor %}
    </tbody>
  </table>
</body>
</html>












<!--
  <h1 style="text-align:center;font-weight:bolder;font-family: 'Courier New', Courier, monospace;font-size:70px">All Registered patients</h1><br>
<!-- <h2 style="font-size:55px;">All Patient Registered</h2> -->

  <!-- {% for r in object_list %}

    <a href="{% url 'detail_record' r.pk %}" style="font-size:20px;padding-left:20px;">{{r.id}} {{r.first_name}} </a><br>

  {% endfor %} -->

templates/records.html
{% extends 'layout.html' %}

{% load static %}
{% block title %}Image Recognition | AI Course-work{% endblock %}
{% block content %}
<div class="container">
  <h1 class="jumbotron">Records</h1>
  <ul>
    {% for record in records %}
      <li><a href="/records/details/{{record.id}}">{{record.first_name}} {{record.last_name}}</a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}